services:
    db:
      image: postgres:17-alpine
      environment:
        - POSTGRES_USER=${DB_USERNAME:-cnampagnon}
        - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
        - POSTGRES_DB=${DB_DATABASE:-cnampagnon}
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - '${DB_PORT:-5432}:5432'
      networks:
        - pg
networks:
  pg:
    external: true
volumes:
  db-data:
